//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEndOfYear
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffTBL
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Department { get; set; }
        public string Type { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual StaffTBL StaffTBL1 { get; set; }
        public virtual StaffTBL StaffTBL2 { get; set; }
    }
}
